### ISSUE TITLE
[Working on this] needs a pathfinder.ini overwrite file for some settings modifications

### ISSUE THREAD

**Issue by november781** [porowns/pathfinder-docker#10]
due to similar names in the settings of, for instance map lifetimes, we need an overwrite pathfinder.ini that gets placed in the /var/www/pathfinder/conf/ folder that can be manually edited and imported with the Dockerfile.

I am attempting this on my fork but cant seem to get pathfinder to see the file.

this change would allow setting admin logins, changing map settings, changing server name (that one can be done in the existing .env file).

help would be appreciated

**Comment by porowns** [comment]
We're not doing any manual configuration file editing anymore, this project is a single image at https://hub.docker.com/repository/docker/kryptedgaming/pathfinder. The user should not be building the image, things must be done with the environment variables

See https://github.com/KryptedGaming/pathfinder-docker/blob/master/entrypoint.sh

**Comment by november781** [comment]
so then I need to find a way to edit the map settings. 

because under personal the settings are the same name as under corp

**Comment by porowns** [comment]
You'd have to go through the lines until you're in the personal section and then do your modifications if you're not able to directly use `sed` on the file

**Comment by porowns** [comment]
Or build an extra file with the shell script and move it into the conf folder

**Comment by november781** [comment]
welp

**Comment by november781** [comment]
> Or build an extra file with the shell script and move it into the conf folder

that is what I am trying to do

**Comment by november781** [comment]
but I cant seem to get the system to recognize the file

**Comment by porowns** [comment]
` manually edited and imported with the Dockerfile` this is the wrong way to approach it, though. You need to modify the entrypoint script to cat out lines and build up the file you want

**Comment by porowns** [comment]
You'll need to modify the docker-compose.yml to do `build: .` instead of pulling from the image

**Comment by porowns** [comment]
OR you can build the image locally `docker build . -t kryptedgaming/pathfinder:latest` and it should pick that up

**Comment by porowns** [comment]
```
version: '2.0'

services:
    db:
        image: mysql:5.7
        volumes:
            - database:/var/lib/mysql
            - ./config/start.sql:/docker-entrypoint-initdb.d/start.sql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_USER: "${MYSQL_USER}"

    pathfinder:
        build: .
        image: kryptedgaming/pathfinder:latest
        env_file: .env
        ports:
            - "8000:80"

volumes:
    database: {}
```
